version: '3.3'

services:
  backend:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    container_name: DjBackend


  myredis:
    image: redis:7.4.1-alpine
    container_name: MyRedisServer