# Generated by Django 4.2.9 on 2025-01-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='A7RWKZRK', max_length=10),
        ),
    ]
