# Generated by Django 4.2.9 on 2025-02-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='F6G4FM5U', max_length=10),
        ),
    ]
