# Generated by Django 4.2.9 on 2025-02-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='CMPTHIEJ', max_length=10),
        ),
    ]
